options(repos = c(CRAN = "https://cran.r-project.org"))
install.packages(c("readr","ggplot2","tidyr"))
install.packages("tidyverse", dependencies = TRUE)
install.packages("rmarkdown", dependencies = TRUE)
install.packages("IRkernel", dependencies = TRUE)
install.packages("skimr", dependencies = TRUE)
install.packages("Rtsne", dependencies = TRUE)
install.packages("glmnet", dependencies = TRUE)
install.packages("broom", dependencies = TRUE)
install.packages("gridExtra", dependencies=TRUE)

IRkernel::installspec(user = FALSE)
